services:
  - type: web
    name: collaborative-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn server.app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ENV
        value: production
    autoDeploy: true
